---
sudo: required
services:
  - docker
branches:
  only:
    - master
language: python
python: "2.7"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/585695e300c1647225df
      - https://api.opsgenie.com/v1/json/travisci?apiKey=2d473151-7b86-415e-9e66-6d5146e14720
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  - DISTRO=ubuntu1604
  - DISTRO=ubuntu1604py3
  - DISTRO=ubuntu1404
  - DISTRO=ubuntu1204
  - DISTRO=fedora23
  - DISTRO=fedora-rawhide
  - DISTRO=centos7
  - DISTRO=centos6

install:
# Install Ansible.
- pip install ansible

# Add ansible.cfg to pick up roles path.
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
# Check the role/playbook's syntax.
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check

# Check Playbook and idempotency on different platforms
- ansible-playbook -i tests/inventory tests/template.yml -e "path=`pwd` distro=$DISTRO"
- docker build -f Dockerfile .
